//
//  HomeScreenModels.swift
//  AGLViperProject
//
//  Created by Ильдар Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeScreenModel {
    
    enum OpenHomeScreenDetails {
        struct Request {
            let index: Int
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
            
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
}
