//
//  HomeScreenPresenter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScreenPresentationLogic {
    func presentHomeScreenOpenDetails(response: HomeScreenModel.OpenHomeScreenDetails.Response)
    func presentHomeScreenChangeControllerMode(response: HomeScreenModel.ChangeControllerMode.Response)
}

class HomeScreenPresenter {
    weak var viewController: HomeScreenDisplayLogic?
}

extension HomeScreenPresenter: HomeScreenPresentationLogic {
    
    func presentHomeScreenChangeControllerMode(response: HomeScreenModel.ChangeControllerMode.Response) {
        let viewModel = HomeScreenModel.ChangeControllerMode.ViewModel(mode: response.mode)
        viewController?.displayHomeScreenChangeControllerMode(viewModel: viewModel)
    }
    
    func presentHomeScreenOpenDetails(response: HomeScreenModel.OpenHomeScreenDetails.Response) {
        let viewModel = HomeScreenModel.OpenHomeScreenDetails.ViewModel()
        viewController?.displayHomeScreenOpenDetails(viewModel: viewModel)
    }
}
