//
//  HomeScreenWorker.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeScreenWorker {
    
    private let networkService: NetworkService = NetworkService()
    
    func getLocalHomeScreenData(completion: @escaping ([HomeScreenData]?) -> Void) {
        let fileName = "HomeScreenData"
        networkService.getDataFromJSON(fileName: fileName, response: completion)
    }
}
