//
//  HomeScreenViewController.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScreenDisplayLogic: class {
    func displayHomeScreenOpenDetails(viewModel: HomeScreenModel.OpenHomeScreenDetails.ViewModel)
    func displayHomeScreenChangeControllerMode(viewModel: HomeScreenModel.ChangeControllerMode.ViewModel)
}

class HomeScreenViewController: UIViewController {
    var interactor: HomeScreenBusinessLogic?
    var router: (NSObjectProtocol & HomeScreenRoutingLogic & HomeScreenDataPassing)?
    
    private var mode: ControllerMode = .viewing
    
    private let activityIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView()
        indicator.translatesAutoresizingMaskIntoConstraints = false
        indicator.color = UIColor.gray
        indicator.style = .large
        return indicator
    }()
    
    private let logoImage: UIImageView = {
        let image = UIImageView()
        image.translatesAutoresizingMaskIntoConstraints = false
        image.contentMode = .center
        image.image = UIImage(named: "ViperLogo")
        return image
    }()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor              = HomeScreenInteractor()
        let presenter               = HomeScreenPresenter()
        let router                  = HomeScreenRouter()
        viewController.interactor   = interactor
        viewController.router       = router
        interactor.presenter        = presenter
        presenter.viewController    = viewController
        router.viewController       = viewController
        router.dataStore            = interactor
    }
    
    // MARK: View lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        view.addSubview(logoImage)
        view.addSubview(activityIndicator)
        
        let constraints: [NSLayoutConstraint] = [
            logoImage.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            logoImage.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            activityIndicator.topAnchor.constraint(equalTo: logoImage.centerYAnchor, constant: 200.0),
            activityIndicator.centerXAnchor.constraint(equalTo: view.centerXAnchor)
        ]
        NSLayoutConstraint.activate(constraints)
        
        openDetailsViewController(index: 0)
    }
    
    private func openDetailsViewController(index: Int) {
        let request = HomeScreenModel.OpenHomeScreenDetails.Request(index: index)
        interactor?.openHomeScreenDetails(request: request)
    }
    
    private func updateNavigationItem() {
        switch mode {
        case .viewing:
            self.activityIndicator.stopAnimating()
            navigationItem.setRightBarButton(nil, animated: true)
        case .editing:()
            
        case .updating:
            self.activityIndicator.startAnimating()
        }
    }
}

extension HomeScreenViewController: HomeScreenDisplayLogic {
    
    func displayHomeScreenChangeControllerMode(viewModel: HomeScreenModel.ChangeControllerMode.ViewModel) {
        mode = viewModel.mode
        updateNavigationItem()
    }
    
    func displayHomeScreenOpenDetails(viewModel: HomeScreenModel.OpenHomeScreenDetails.ViewModel) {
        self.router?.routeToRestaurantMenu()
    }
}
