//
//  BasketModels.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 13.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BasketModel {
    struct DisplayedSection: Equatable {
        
        enum SectionType: Equatable {
            case basket
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case details(imageName: String, name: String, details: String, price: Int32)
            }
            let type: CellType
        }
        
        let cells: [DisplayedCell]
    }
    
    enum FetchBasketData {
        struct Request {
        }
        
        struct Response {
            let detailsData: [BasketData]
        }
        
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
    
    enum ClearDataStore {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum OpenBasketDetails {
        struct Request {
            let index: Int
        }
        
        struct Response {
            let index: Int
        }
        
        struct ViewModel {
            let index: Int
        }
    }
}
