//
//  SecondModels.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 01.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Second {
    
    struct DisplayedSection: Equatable {
        
        enum SectionType: Equatable {
            case details
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                
                case info(title: String)
                case description(title: String, imageName: String)
            }
            
            let type: CellType
        }
        
        let cells: [DisplayedCell]
        let header: String?
        let footer: String?
    }
    
    enum FetchData {
        
        struct Request {
            
        }
        
        struct Response {
            let secondData: Options?
        }
        
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
            
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
    
}
