//
//  SecondRouter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 01.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SecondRoutingLogic {

}

protocol SecondDataPassing {
    var dataStore: SecondDataStore? { get }
}

class SecondRouter: NSObject, SecondRoutingLogic, SecondDataPassing {
    
    weak var viewController: SecondViewController?
    var dataStore: SecondDataStore?
    
    // MARK: Routing
    
    
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: SecondViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: SecondDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
