//
//  FirstPresenter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstPresentationLogic {
    func presentFetchedData(response: First.FetchData.Response)
    func presentOpenDetails(response: First.OpenDetails.Response)

}

class FirstPresenter {
    
    weak var viewController: FirstDisplayLogic?
    
}

extension FirstPresenter: FirstPresentationLogic {
    
    func presentFetchedData(response: First.FetchData.Response) {
        let viewModel = First.FetchData.ViewModel(mainData: response.mainData)
        viewController?.displayFetchedData(viewModel: viewModel)
    }
    
    func presentOpenDetails(response: First.OpenDetails.Response) {
        let viewModel = First.OpenDetails.ViewModel(data: response.data)
        viewController?.displayOpenDetails(viewModel: viewModel)
    }
}
