//
//  FirstModels.swift
//  AGLViperProject
//
//  Created by Ильдар Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum First {
    
    enum FetchData {
        
        struct Request {
            
        }
        
        struct Response {
            let mainData: [Options]
        }
        
        struct ViewModel {
            let mainData: [Options]
        }
    }
    
    enum OpenDetails {
        struct Request {
            let index: Int
        }
        
        struct Response {
            let data: Options
        }
        
        struct ViewModel {
            let data: Options
        }
    }
}
