//
//  FirstWorker.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FirstWorker {
    
    private let networkService: NetworkService = NetworkService()
    
    func getLocalFirstData(completion: @escaping ([Options]?) -> Void) {
        let fileName = "Options"
        networkService.getDataFromJSON(fileName: fileName, response: completion)
    }
    
    func getTitleOptions(completion: @escaping ([TitleOptions]?) -> Void) {
        let fileName = "TitleOptions"
        networkService.getDataFromJSON(fileName: fileName, response: completion)
    }
    
}
