//
//  FirstRouter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 30.09.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FirstRoutingLogic {
    func routeToSecond()
}

protocol FirstDataPassing {
    var dataStore: FirstDataStore? { get }
}

class FirstRouter: NSObject, FirstDataPassing {
    
    weak var viewController: FirstViewController?
    var dataStore: FirstDataStore?
    
    // MARK: Navigation
    
    func navigateToSecond(source: FirstViewController, destination: SecondViewController)
    {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToSecond(source: FirstDataStore, destination: inout SecondDataStore)
    {
        destination.option = source.data
    }
}

extension FirstRouter: FirstRoutingLogic {
    
    // MARK: Routing
    func routeToSecond() {
        guard let viewController = self.viewController else { return }
        let secondVC = SecondViewController()
        guard let sourceDataStore = self.dataStore, var destinationDataStore = secondVC.router?.dataStore else { return }
        self.passDataToSecond(source: sourceDataStore, destination: &destinationDataStore)
        self.navigateToSecond(source: viewController, destination: secondVC)
    }
    
}
