//
//  RestaurantDetailsRouter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RestaurantDetailsRoutingLogic {
    func routeToBasketVC()

}

protocol RestaurantDetailsDataPassing {
    var dataStore: RestaurantDetailsDataStore? { get }
}

class RestaurantDetailsRouter: NSObject, RestaurantDetailsRoutingLogic, RestaurantDetailsDataPassing {
    
    weak var viewController: RestaurantDetailsViewController?
    var dataStore: RestaurantDetailsDataStore?
    
    func navigateToBasket(source: RestaurantDetailsViewController, destination: BasketViewController) {
        let navigationVC = UINavigationController(rootViewController: destination)
        source.navigationController?.present(navigationVC, animated: true, completion: nil)
    }
    
    func routeToBasketVC() {
        guard let viewController = self.viewController else { return }
        
        let basketVC = BasketViewController()
        self.navigateToBasket(source: viewController, destination: basketVC)
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: RestaurantDetailsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: RestaurantDetailsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
