//
//  RestaurantDetailsInteractor.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantDetailsBusinessLogic {
    func fetchRestaurantDetailsData(request: RestaurantDetailsModel.FetchRestaurantDetailsData.Request)
}

protocol RestaurantDetailsDataStore {
    var option: HomeScreenData? { get set }
}

class RestaurantDetailsInteractor: RestaurantDetailsDataStore {
    var presenter: RestaurantDetailsPresentationLogic?
    
    private let worker: RestaurantDetailsWorker = RestaurantDetailsWorker()
    
    private var mutableOption: HomeScreenData?
    
    var option: HomeScreenData? {
        didSet {
            guard option != nil, mutableOption == nil else { return }
            mutableOption = option
        }
    }
    
    private var mode: ControllerMode = .viewing {
        didSet {
            let response = RestaurantDetailsModel.ChangeControllerMode.Response(mode: mode)
            presenter?.presentRestaurantDetailsControllerMode(response: response)
        }
    }
}

extension RestaurantDetailsInteractor: RestaurantDetailsBusinessLogic {
    
    func fetchRestaurantDetailsData(request: RestaurantDetailsModel.FetchRestaurantDetailsData.Request) {
        let response = RestaurantDetailsModel.FetchRestaurantDetailsData.Response(detailsData: self.mutableOption)
        self.presenter?.presentFetchedRestaurantDetailsData(response: response)
    }
}
