//
//  RestaurantDetailsModels.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RestaurantDetailsModel {
    struct DisplayedSection: Equatable {
        
        enum SectionType: Equatable {
            case details
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case details(title: String, imageName: String, descriptionText: String, price: Int32, priceText: String, header: String?, footer: String?, count: Int32?)
            }
            let type: CellType
        }
        
        let cells: [DisplayedCell]
    }
    
    enum FetchRestaurantDetailsData {
        struct Request {
        }
        
        struct Response {
            let detailsData: HomeScreenData?
        }
        
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
    
    enum SetBasketData {
        struct Request {
            let title: String
            let imageName: String
            let details: String
            let price: Int32
            let priceText: String
            let count: Int32
        }
        
        struct Response {
            let detailsData: BasketData
        }
        
        struct ViewModel {
            let detailsData: BasketData
        }
    }
}
