//
//  RestaurantDetailsViewController.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RestaurantDetailsDisplayLogic: class {
    func displayRestaurantDetailsControllerMode(viewModel: RestaurantDetailsModel.ChangeControllerMode.ViewModel)
    func displayRestaurantDetailsFetchedData(viewModel: RestaurantDetailsModel.FetchRestaurantDetailsData.ViewModel)
}

class RestaurantDetailsViewController: UIViewController {
    
    var interactor: RestaurantDetailsBusinessLogic?
    var router: (NSObjectProtocol & RestaurantDetailsRoutingLogic & RestaurantDetailsDataPassing)?
    
    private var mode: ControllerMode = .viewing
    
    lazy var alertController: UIAlertController = UIAlertController()
    
    private let activityIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView()
        indicator.translatesAutoresizingMaskIntoConstraints = false
        indicator.color = UIColor.blue
        indicator.startAnimating()
        return indicator
    }()
    
    private let collectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.estimatedItemSize = CGSize(width: UIScreen.main.bounds.size.width, height: UIScreen.main.bounds.size.height)
        let collectionView = UICollectionView(frame: CGRect.zero, collectionViewLayout: layout)
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        collectionView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
        collectionView.backgroundColor = UIColor.white
        collectionView.register(RestaurantDetailsView.self, forCellWithReuseIdentifier: String(describing: RestaurantDetailsView.self))
        return collectionView
    }()
    
    private var displayedSections: [RestaurantDetailsModel.DisplayedSection] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController          = self
        let interactor              = RestaurantDetailsInteractor()
        let presenter               = RestaurantDetailsPresenter()
        let router                  = RestaurantDetailsRouter()
        viewController.interactor   = interactor
        viewController.router       = router
        interactor.presenter        = presenter
        presenter.viewController    = viewController
        router.viewController       = viewController
        router.dataStore            = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Описание"
        
        view.addSubview(collectionView)
        collectionView.frame = view.bounds
        collectionView.delegate = self
        collectionView.dataSource = self
        
        fetchRestaurantDetailsData()
    }
    
    private func fetchRestaurantDetailsData() {
        let request = RestaurantDetailsModel.FetchRestaurantDetailsData.Request()
        interactor?.fetchRestaurantDetailsData(request: request)
    }
    
    private func updateNavigationItem() {
        switch mode {
        case .viewing:
            navigationItem.setRightBarButton(nil, animated: true)
        case .editing:()
            
        case .updating:
            let rightItem = UIBarButtonItem(customView: activityIndicator)
            navigationItem.setRightBarButton(rightItem, animated: true)
        }
    }
}

extension RestaurantDetailsViewController: RestaurantDetailsDisplayLogic {
    
    func displayRestaurantDetailsControllerMode(viewModel: RestaurantDetailsModel.ChangeControllerMode.ViewModel) {
        mode = viewModel.mode
        updateNavigationItem()
    }
    
    func displayRestaurantDetailsFetchedData(viewModel: RestaurantDetailsModel.FetchRestaurantDetailsData.ViewModel) {
        displayedSections = viewModel.displayedSection
        collectionView.reloadData()
    }
}

extension RestaurantDetailsViewController: UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        collectionView.deselectItem(at: indexPath, animated: true)
    }
    
}

extension RestaurantDetailsViewController: UICollectionViewDataSource {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return displayedSections[section].cells.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let displayedSection = displayedSections[indexPath.section]
        let cellType = displayedSection.cells[indexPath.row].type
        
        switch cellType {
        case .description(title: let title, imageName: let imageName, descriptionText: let description, priceText: let priceText, header: let header, footer: let footer):
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: RestaurantDetailsView.self), for: indexPath) as! RestaurantDetailsView
            cell.setupValue(titleText: title, imageName: imageName, descriptionText: description, priceText: priceText, headerText: header, footerText: footer)
            return cell
        }
    }
}
