//
//  ShopCartModels.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 13.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShopCart {
    struct DisplayedSection: Equatable {
        
        enum SectionType: Equatable {
            case shopCart
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case description(title: String, priceText: String)
            }
            let type: CellType
        }
        
        let cells: [DisplayedCell]
    }
    
    enum FetchShopCartData {
        struct Request {
            
        }
        
        struct Response {
            let detailsData: [HomeScreenData]
        }
        
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
            
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
}
