//
//  ShopCartInteractor.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 13.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopCartBusinessLogic {
    func fetchRestaurantMenuData(request: ShopCart.FetchShopCartData.Request)
    func openRestaurantMenuDetails(request: ShopCart.ChangeControllerMode.Request)
    func openShopCartData(request: ShopCart.FetchShopCartData.Request)

}

protocol ShopCartDataStore {
    var shopCartData: [HomeScreenData]? { get set }
}

class ShopCartInteractor: ShopCartDataStore {
    var shopCartData: [HomeScreenData]?
    
    var presenter: ShopCartPresentationLogic?
    
    private let worker: ShopCartWorker = ShopCartWorker()
    
    private var mode: ControllerMode = .viewing {
        didSet {
            let response = ShopCart.ChangeControllerMode.Response(mode: self.mode)
            self.presenter?.presentShopCartControllerMode(response: response)
        }
    }
}

extension ShopCartInteractor: ShopCartBusinessLogic {
    
    func openShopCartData(request: ShopCart.FetchShopCartData.Request) {
        print("hah")
    }
    
    func fetchRestaurantMenuData(request: ShopCart.FetchShopCartData.Request) {
        let response = ShopCart.FetchShopCartData.Response(detailsData: self.shopCartData ?? [])
        self.presenter?.presentShopCartFetchedData(response: response)
    }
    
    func openRestaurantMenuDetails(request: ShopCart.ChangeControllerMode.Request) {
        let response = ShopCart.ChangeControllerMode.Response(mode: self.mode)
        self.presenter?.presentShopCartControllerMode(response: response)
    }
}
