//
//  ShopCartRouter.swift
//  AGLViperProject
//
//  Created by Раис Аглиуллов on 13.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShopCartRoutingLogic {
    
}

protocol ShopCartDataPassing {
    var dataStore: ShopCartDataStore? { get }
}

class ShopCartRouter: NSObject, ShopCartDataPassing {
    
    weak var viewController: ShopCartViewController?
    var dataStore: ShopCartDataStore?
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ShopCartViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ShopCartDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}

extension ShopCartRouter: ShopCartRoutingLogic {
    
}
